package com.sjlh.hotel.common.push;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

/**
 * Person generated by hbm2java
 */
public class Person  implements java.io.Serializable {
     private Long id;
     private String name;
     private String lobby;
     private Integer sex;
     private LocalDateTime createTime;
     private LocalDate birthday;
     private Boolean vip;
     private Set<Factory> factories = new HashSet<Factory>(0);

    public Person() {
    }

    public Person(String name, String lobby, Integer sex, LocalDateTime createTime, LocalDate birthday, Boolean vip, Set<Factory> factories) {
       this.name = name;
       this.lobby = lobby;
       this.sex = sex;
       this.createTime = createTime;
       this.birthday = birthday;
       this.vip = vip;
       this.factories = factories;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getLobby() {
        return this.lobby;
    }
    
    public void setLobby(String lobby) {
        this.lobby = lobby;
    }
    
    public Integer getSex() {
        return this.sex;
    }
    
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public LocalDate getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(LocalDate birthday) {
        this.birthday = birthday;
    }

    public Boolean getVip() {
        return this.vip;
    }
    
    public void setVip(Boolean vip) {
        this.vip = vip;
    }

    public Set<Factory> getFactories() {
        return this.factories;
    }
    
    public void setFactories(Set<Factory> factories) {
        this.factories = factories;
    }
}